export const actionsTypes = {
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILED: "FETCH_PRODUCTS_FAILED",
  FETCH_PRODUCTDETAIL_SUCCESS: "FETCH_PRODUCTDETAIL_SUCCESS",
  FETCH_PRODUCTSDETAIL_FAILED: "FETCH_PRODUCTSDETAIL_FAILED",

  FETCH_RESULTSEARCH_SUCCESS: "FETCH_RESULTSEARCH_SUCCESS",
  UPDATE_RESULTSEARCH_SUCCESS: "UPDATE_RESULTSEARCH_SUCCESS",
  FETCH_RESULTSEARCH_FAILED: "FETCH_RESULTSEARCH_FAILED",

  GET_ALL_CART_ITEM_SUCCESS: "GET_ALL_CART_ITEM_SUCCESS",
  GET_ALL_CART_ITEM_FAILED: "GET_ALL_CART_ITEM_FAILED",
  REMOVE_PRODUCT_DETAIL: "REMOVE_PRODUCT_DETAIL",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILD: "ADD_TO_CART_FAILD",
  UPDATE_CART: "UPDATE_CART",
  UPDATE_IS_SELECT_CARTITEM: "UPDATE_IS_SELECT_CARTITEM",
  SELECTED_ALL_CART_ITEM: "SELECTED_ALL_CART_ITEM",
  DELETE_CART: "DELETE_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",

  //auth
  LOGIN_SUSSESS: "LOGIN_SUSSESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_CLEAR: "LOGIN_CLEAR",
  LOGIN_LOADING: "LOGIN_LOADING",
  NO_INTERNET: "NO_INTERNET",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILD: "LOGOUT_FAILD",
  UPDATE_TOKEN: "UPDATE_TOKEN",

  //USER
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILD: "CREATE_USER_FAILD",

  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILD: "UPDATE_USER_FAILD",
};
